project:
  type: website
  output-dir: docs

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Labs"
        menu:
          - text: "Lab 1"
            href: Lab1.qmd
          - text: "Lab 2"
            href: Lab2.qmd
          - text: "Lab 3"
            href: Lab3.qmd
          - text: "Lab 4"
            href: Lab4.qmd
          - text: "Lab 5"
            href: Lab5.qmd
          - text: "Lab 6"
            href: Lab6.qmd
          - text: "Lab 7"
            href: Lab7.qmd
      - href: resources.qmd
        text: Resources
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



