project:
  type: website
  output-dir: docs

website:
  title: "Esteban Gonzalez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects  
      - text: "E155 Labs"
        menu:
          - text: "Lab 1: Soldering & FPGA"
            href: Lab1.qmd
          - text: "Lab 2: FPGA SPI Interface"
            href: Lab2.qmd
          - text: "Lab 3: Keypad & LED Driver"
            href: Lab3.qmd
          - text: "Lab 4: Audio DAC & PWM"
            href: Lab4.qmd
          - text: "Lab 5"
            href: Lab5.qmd
          - text: "Lab 6"
            href: Lab6.qmd
          - text: "Lab 7 "
            href: Lab7.qmd
      - href: Esteban_Gonzalez_Resume.pdf
        text: Resume
      - href: resources.qmd
        text: Resources
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true



